# azure-pipelines.yml
trigger:
- none

parameters:
- name: targetApp
  displayName: Target Application(s) to scan
  type: string
  default: 'agent'
  values:
  - 'admin'
  - 'agent'
  - 'both'

- name: scanType
  displayName: Type of ZAP scan
  type: string
  default: 'baseline'
  values:
  - 'baseline'
  - 'full'
  - 'api'

- name: reportTemplate
  displayName: ZAP Report Template
  type: string
  default: 'modern'
  values:
  - 'modern'
  - 'traditional-html'
  - 'traditional-html-plus'
  - 'traditional-json'
  - 'sarif-json'
  - 'pdf'

- name: adminUrl
  displayName: Admin Application URL
  type: string
  default: 'https://qa.app-np.neovance.com/'

- name: agentUrl
  displayName: Agent Application URL
  type: string
  default: 'https://qa-agent.app-np.neovance.com/'

- name: adminApiSpec
  displayName: Admin API OpenAPI URL
  type: string
  default: 'https://qa.app-np.neovance.com/swagger.json'

- name: agentApiSpec
  displayName: Agent API OpenAPI URL
  type: string
  default: 'https://qa-agent.app-np.neovance.com/swagger.json'

stages:
- stage: ZAP_Scan_Stage
  displayName: "Run ZAP Scan"
  jobs:

  # Admin Scan
  - job: AdminScan
    displayName: "ZAP Scan - Admin"
    condition: or(eq('${{ parameters.targetApp }}','admin'), eq('${{ parameters.targetApp }}','both'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: zap-template.yml
      parameters:
        targetUrl: ${{ parameters.adminUrl }}
        apiSpecUrl: ${{ parameters.adminApiSpec }}
        appName: 'admin'
        scanType: ${{ parameters.scanType }}
        reportTemplate: ${{ parameters.reportTemplate }}

  # Agent Scan
  - job: AgentScan
    displayName: "ZAP Scan - Agent"
    condition: or(eq('${{ parameters.targetApp }}','agent'), eq('${{ parameters.targetApp }}','both'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: zap-template.yml
      parameters:
        targetUrl: ${{ parameters.agentUrl }}
        apiSpecUrl: ${{ parameters.agentApiSpec }}
        appName: 'agent'
        scanType: ${{ parameters.scanType }}
        reportTemplate: ${{ parameters.reportTemplate }}
