# azure-pipelines.yml
trigger:
- none

parameters:
- name: scanType
  displayName: Type of ZAP scan
  type: string
  default: 'baseline'
  values:
  - 'baseline'
  - 'full'
  - 'api'

- name: reportTemplate
  displayName: ZAP Report Template
  type: string
  default: 'traditional-html'
  values:
  - traditional-html
  - traditional-json
  - sarif-json
  - traditional-pdf

- name: adminUrl
  displayName: Admin Application URL
  type: string
  default: 'https://qa.app-np.neovance.com/'

- name: agentUrl
  displayName: Agent Application URL
  type: string
  default: 'https://qa-agent.app-np.neovance.com/'

stages:
- stage: ZAP_Scan_Stage
  displayName: "Run ZAP Scan"
  jobs:

  # Always run admin scan
  - job: AdminScan
    displayName: "ZAP Scan - Admin"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: zap-template.yml
      parameters:
        targetUrl: ${{ parameters.adminUrl }}
        appName: 'admin'
        scanType: ${{ parameters.scanType }}
        reportTemplate: ${{ parameters.reportTemplate }}

  # Always run agent scan
  - job: AgentScan
    displayName: "ZAP Scan - Agent"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: zap-template.yml
      parameters:
        targetUrl: ${{ parameters.agentUrl }}
        appName: 'agent'
        scanType: ${{ parameters.scanType }}
        reportTemplate: ${{ parameters.reportTemplate }}
